<x-app-layout>
    @include('partials.nav')
    @include('partials.slider')
    @include('partials.service')
    @include('partials.features')
    @include('partials.pricing')
    @include('partials.team')
    @include('partials.faq')
    @include('partials.blog')
</x-app-layout>
