<x-app-layout>
    @include('partials.header')
    @include('partials.slider')
    @include('partials.service')
    @include('partials.features')
    @include('partials.pricing')
    @include('partials.team')
    @include('partials.faq')
    @include('partials.blog')
    @include('partials.contact')
    @include('partials.footer')
</x-app-layout>
